import React from "react";
// import { Postulation } from "../components/Postulation/Postulacion";
import { PersonalForm } from "../components/PersonalForm/PersonalForm";

export default function Home() {
  return (
    <div>
      <PersonalForm />
    </div>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{" "}
    //       <code className={styles.code}>pages/index.js</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/master/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>

    //     <p>
    //       <a
    //         className="btn btn-primary"
    //         data-bs-toggle="collapse"
    //         href="#collapseExample"
    //         role="button"
    //         aria-expanded="false"
    //         aria-controls="collapseExample"
    //       >
    //         Link with href
    //       </a>
    //       <button
    //         className="btn btn-primary"
    //         type="button"
    //         data-bs-toggle="collapse"
    //         data-bs-target="#collapseExample"
    //         aria-expanded="false"
    //         aria-controls="collapseExample"
    //       >
    //         Button with data-bs-target
    //       </button>
    //     </p>
    //     <div className="collapse" id="collapseExample">
    //       <div className="card card-body">
    //         Some placeholder content for the collapse component. This panel is
    //         hidden by default but revealed when the user activates the relevant
    //         trigger.
    //       </div>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{" "}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div></div>
  );
}
